// Portado do ERP Universal: backend/src/pdf/helpers/theme.js.
export const UNIVERSAL_PDF_THEME = {
  blue: '#1e3a8a',
  blueLine: '#1d4ed8',
  blueSoft: '#eff6ff',
  navy: '#102a56',
  text: '#1f2937',
  muted: '#64748b',
  border: '#d1d5db',
  borderSoft: '#e5e7eb',
  panel: '#f8fafc',
  warningPanel: '#fff5f5',
  warningBorder: '#fecaca',
  tableHeaderBackground: '#f4f7fb',
  tableOuterBorder: '#d8e1ec',
  tableHorizontalBorder: '#dce4ee',
  tableVerticalBorder: '#e1e7ef',
  tableHeaderDivider: '#d5dfeb',
  tableOuterBorderWidth: 0.5,
  tableHorizontalBorderWidth: 0.4,
  tableVerticalBorderWidth: 0.3,
  tableHeaderDividerWidth: 0.5,
  pageMargin: 42,
  footerHeight: 24,
  commercialSignatureHeight: 70,
};
