import { randomUUID } from 'node:crypto';
import { query, transaction } from '../database/pool.js';
import { httpError } from '../utils/httpError.js';
import { logAudit } from './auditService.js';
import { hasPermission } from './permissionService.js';
import { normalizeMeasurementUnitCode, resolveMeasurementUnit } from './measurementUnitService.js';

const GENERIC_WORDS = new Set(['rolamento','chapa','parafuso','motor','ferramenta','peca','material','produto','unidade','kit','conjunto']);
const HEADER_ALIASES = {
  codigo:'supplier_item_code', codigofornecedor:'supplier_item_code', codigo_fornecedor:'supplier_item_code', code:'supplier_item_code',
  descricao:'description', description:'description', produto:'description', item:'description',
  quantidade:'quantity', qtd:'quantity', qty:'quantity',
  unidade:'unit', un:'unit',
  valor:'unit_price', valorunitario:'unit_price', valor_unitario:'unit_price', preco:'unit_price', preco_unitario:'unit_price',
  valortotal:'total_price', valor_total:'total_price', total:'total_price',
  marca:'brand', brand:'brand', observacao:'notes', observacoes:'notes', observacao_item:'notes', notes:'notes',
};

export function normalizePurchaseText(value) {
  return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ').trim().replace(/\s+/g, ' ');
}

export function parseBrazilianNumber(value) {
  const raw = String(value ?? '').trim().replace(/R\$\s?/gi, '').replace(/\s/g, '');
  if (!raw) return null;
  let normalized = raw;
  if (raw.includes(',') && raw.includes('.')) normalized = raw.lastIndexOf(',') > raw.lastIndexOf('.') ? raw.replace(/\./g, '').replace(',', '.') : raw.replace(/,/g, '');
  else if (raw.includes(',')) normalized = raw.replace(/\./g, '').replace(',', '.');
  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : null;
}

function parseCsvRows(content, delimiter) {
  const rows=[];let row=[];let value='';let quoted=false;
  for(let index=0;index<String(content).length;index+=1){const char=content[index];if(char==='"'){if(quoted&&content[index+1]==='"'){value+='"';index+=1;}else quoted=!quoted;}else if(char===delimiter&&!quoted){row.push(value);value='';}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&content[index+1]==='\n')index+=1;row.push(value);if(row.some(cell=>cell.trim()))rows.push(row);row=[];value='';}else value+=char;}
  row.push(value);if(row.some(cell=>cell.trim()))rows.push(row);return rows;
}

function normalizedHeader(value) { return normalizePurchaseText(value).replace(/ /g, '_'); }
function detectDelimiter(content) {const first=String(content).split(/\r?\n/).find(line=>line.trim())||'';return (first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';}
function itemResult(item,lineNumber,warnings=[],errors=[],inferred=[]){return{line_number:lineNumber,...item,warnings,errors,inferred_fields:inferred,status:errors.length?'invalid':warnings.length?'warning':'valid'};}

export function parseCsvImport(content, columnMapping={}) {
  const delimiter=detectDelimiter(content);const rows=parseCsvRows(content,delimiter);if(!rows.length)return{delimiter,items:[],headers:[],unrecognized_headers:[]};
  const headers=rows[0].map(cell=>cell.trim());const mapped=headers.map((header,index)=>columnMapping[header]||columnMapping[index]||HEADER_ALIASES[normalizedHeader(header)]||null);const unrecognized_headers=headers.filter((_,index)=>!mapped[index]);
  const items=rows.slice(1).map((cells,index)=>{const raw={};mapped.forEach((field,column)=>{if(field)raw[field]=cells[column]?.trim()||'';});const warnings=[];const errors=[];const description=String(raw.description||'').trim();if(!description)errors.push('Descrição não identificada.');const quantity=parseBrazilianNumber(raw.quantity);const unitPrice=parseBrazilianNumber(raw.unit_price);const totalPrice=parseBrazilianNumber(raw.total_price);if(raw.quantity&&quantity===null)errors.push('Quantidade inválida.');if(raw.unit_price&&unitPrice===null)errors.push('Valor unitário inválido.');if(raw.total_price&&totalPrice===null)errors.push('Valor total inválido.');if(quantity==null)warnings.push('Quantidade não informada.');if(!raw.unit)warnings.push('Unidade não informada.');if(unitPrice==null&&totalPrice==null)warnings.push('Preço não informado.');return itemResult({supplier_item_code:raw.supplier_item_code||null,description,quantity,unit:raw.unit||null,unit_price:unitPrice,total_price:totalPrice,brand:raw.brand||null,notes:raw.notes||null},index+2,warnings,errors,[]);});
  return{delimiter,headers,mapped_headers:mapped,unrecognized_headers,items};
}

export function parseTextImport(content) {
  const lines=String(content||'').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);
  return lines.map((line,index)=>{const warnings=[];const errors=[];const inferred=[];let item={supplier_item_code:null,description:'',quantity:null,unit:null,unit_price:null,total_price:null,brand:null,notes:null};
    const pipe=line.split('|').map(part=>part.trim());
    if(pipe.length>=2){item.description=pipe[0];item.quantity=parseBrazilianNumber(pipe[1]);item.unit=pipe[2]||null;item.unit_price=parseBrazilianNumber(pipe[3]);item.notes=pipe.slice(4).join(' | ')||null;inferred.push(...['description','quantity',...(item.unit?['unit']:[]),...(item.unit_price!=null?['unit_price']:[])]);}
    else {const match=line.match(/^\s*(?:(\S+)\s+-\s+)?(.+?)\s+-\s+([\d.,]+)\s+([\p{L}\d.]+)\s+-\s+(?:R\$\s*)?([\d.,]+)(?:\s+-\s+(.+))?$/u);if(match){item={...item,supplier_item_code:match[1]||null,description:match[2].trim(),quantity:parseBrazilianNumber(match[3]),unit:match[4],unit_price:parseBrazilianNumber(match[5]),notes:match[6]||null};inferred.push('supplier_item_code','description','quantity','unit','unit_price');}else{const moneyMatch=line.match(/^(.*?)(?:\s+[-|]\s+)?(?:R\$\s*)?([\d.]+,\d{2})$/);item.description=(moneyMatch?.[1]||line).trim();item.unit_price=moneyMatch?parseBrazilianNumber(moneyMatch[2]):null;inferred.push('description');if(moneyMatch){inferred.push('unit_price');warnings.push('Valor interpretado como unitário; confirme antes de salvar.');}}}
    if(!item.description)errors.push('Descrição não identificada.');if(item.quantity==null)warnings.push('Quantidade não identificada; informe manualmente.');if(!item.unit)warnings.push('Unidade não identificada; informe manualmente.');return itemResult(item,index+1,warnings,errors,inferred);
  });
}

function scoreProduct(item,product) {
  const input=normalizePurchaseText([item.description,item.brand,item.supplier_item_code].filter(Boolean).join(' '));const target=normalizePurchaseText([product.name,product.internal_code,product.aliases].filter(Boolean).join(' '));const inputTokens=new Set(input.split(' ').filter(Boolean));const targetTokens=new Set(target.split(' ').filter(Boolean));const inputNumbers=[...inputTokens].filter(token=>/\d/.test(token));const targetNumbers=new Set([...targetTokens].filter(token=>/\d/.test(token)));let score=0;const reasons=[];
  if(item.supplier_item_code&&product.internal_code&&normalizePurchaseText(item.supplier_item_code)===normalizePurchaseText(product.internal_code)){score+=80;reasons.push('código interno exato');}
  const matchedNumbers=inputNumbers.filter(token=>targetNumbers.has(token));if(matchedNumbers.length){score+=matchedNumbers.length*45;reasons.push(`modelo/número ${matchedNumbers.join(', ')}`);}
  const specific=[...inputTokens].filter(token=>token.length>2&&!GENERIC_WORDS.has(token)&&!/^\d+$/.test(token));const matchedSpecific=specific.filter(token=>targetTokens.has(token));if(matchedSpecific.length){score+=matchedSpecific.length*12;reasons.push(`termos ${matchedSpecific.join(', ')}`);}
  const generic=[...inputTokens].filter(token=>GENERIC_WORDS.has(token)&&targetTokens.has(token));score+=generic.length*2;if(item.unit&&product.last_units?.includes(String(item.unit).toLowerCase()))score+=4;if(item.brand&&target.includes(normalizePurchaseText(item.brand)))score+=8;if(!product.is_active)score-=30;
  const hasStrongSignal=matchedNumbers.length>0||matchedSpecific.length>0||score>=70;return{score:Math.max(0,score),reasons,hasStrongSignal};
}

export async function suggestImportedItem(item,supplierId=null,limit=12){
  if(supplierId&&item.supplier_item_code){const exact=await query(`SELECT m.*,p.name product_name,p.internal_code,p.is_active product_is_active FROM supplier_item_mappings m LEFT JOIN products p ON p.id=m.internal_product_id WHERE m.supplier_id=$1 AND lower(m.supplier_item_code)=lower($2) AND m.is_active=TRUE LIMIT 1`,[supplierId,item.supplier_item_code]);if(exact.rows[0]?.internal_product_id)return{match_status:'automatic',automatic_mapping:exact.rows[0],suggestions:[],more_suggestions:[],warnings:[]};}
  const products=(await query(`SELECT p.id,p.name,p.internal_code,p.is_active,COALESCE(string_agg(DISTINCT m.supplier_item_description,' '),'') aliases,COALESCE(array_agg(DISTINCT lower(m.last_unit)) FILTER(WHERE m.last_unit IS NOT NULL),'{}') last_units,COALESCE(array_agg(DISTINCT m.supplier_item_code) FILTER(WHERE m.supplier_id=$1 AND m.supplier_item_code IS NOT NULL),'{}') supplier_codes FROM products p LEFT JOIN supplier_item_mappings m ON m.internal_product_id=p.id GROUP BY p.id ORDER BY p.is_active DESC,p.name LIMIT 500`,[supplierId])).rows;
  const allScored=products.map(product=>{const scoredProduct={...product,...scoreProduct(item,product)};const currentCode=normalizePurchaseText(item.supplier_item_code);const otherCodes=(product.supplier_codes||[]).filter(code=>normalizePurchaseText(code)!==currentCode);return{...scoredProduct,mapping_warning:otherCodes.length?`Este produto já possui outros códigos deste fornecedor: ${otherCodes.join(', ')}`:null};}).sort((a,b)=>(Number(b.is_active)-Number(a.is_active))||b.score-a.score||a.name.localeCompare(b.name)).filter((product,index,list)=>list.findIndex(other=>other.id===product.id)===index);
  const scored=allScored.filter(product=>product.hasStrongSignal&&product.score>=12).slice(0,limit);const fallback=scored.length?[]:allScored.filter(product=>product.is_active).slice(0,Math.min(limit,10));
  return{match_status:scored.length?'possible':'unlinked',automatic_mapping:null,suggestions:scored.slice(0,2),more_suggestions:[...scored.slice(2),...fallback],warnings:fallback.length?['Nenhuma correspondência forte; selecione um Produto ou crie um preliminar.']:[]};
}

export async function previewImport(payload,user){const sourceType=payload.source_type==='csv'?'csv':'text';const parsed=sourceType==='csv'?parseCsvImport(payload.content,payload.column_mapping||{}):{items:parseTextImport(payload.content),headers:[],unrecognized_headers:[]};const sessionId=randomUUID();const items=[];for(const item of parsed.items){let unit_info=null;if(item.unit){unit_info=await resolveMeasurementUnit(item.unit,undefined,{allowLegacy:true});if(!unit_info.is_legacy)item.unit=unit_info.code;else item.warnings=[...(item.warnings||[]),`Unidade legada não reconhecida: ${item.unit}. Selecione uma unidade do catálogo.`];}items.push({...item,unit_info,matching:item.status==='invalid'?{match_status:'unlinked',suggestions:[],more_suggestions:[]}:await suggestImportedItem(item,payload.supplier_id||null)});}await transaction(client=>logAudit(client,{entityType:'purchase_import',entityId:sessionId,action:'import_started',newValue:{context:payload.context||'direct_quote',source_type:sourceType,line_count:items.length},userId:user.id}));return{session_id:sessionId,source_type:sourceType,...parsed,items,summary:{valid:items.filter(i=>i.status==='valid').length,warnings:items.filter(i=>i.status==='warning').length,invalid:items.filter(i=>i.status==='invalid').length}};}

async function upsertMapping(client,item,supplierId,userId){if(!supplierId||!item.save_link)return null;const code=String(item.supplier_item_code||'').trim()||null;const description=String(item.description||'').trim();const normalized=normalizePurchaseText(description);const existing=code?(await client.query('SELECT * FROM supplier_item_mappings WHERE supplier_id=$1 AND lower(supplier_item_code)=lower($2) ORDER BY is_active DESC,updated_at DESC LIMIT 1',[supplierId,code])).rows[0]:(await client.query('SELECT * FROM supplier_item_mappings WHERE supplier_id=$1 AND supplier_item_code IS NULL AND normalized_description=$2 ORDER BY is_active DESC,updated_at DESC LIMIT 1',[supplierId,normalized])).rows[0];let row;if(existing){row=(await client.query(`UPDATE supplier_item_mappings SET supplier_item_description=$1,normalized_description=$2,internal_product_id=$3,material_group_id=$4,brand=$5,last_unit=$6,last_price=COALESCE($7,last_price),last_seen_at=NOW(),is_active=TRUE,updated_at=NOW() WHERE id=$8 RETURNING *`,[description,normalized,item.internal_product_id||null,item.material_group_id||null,item.brand||null,item.unit||null,item.unit_price??null,existing.id])).rows[0];await logAudit(client,{entityType:'supplier_item_mapping',entityId:row.id,action:existing.is_active?'mapping_updated':'mapping_reactivated',previousValue:existing,newValue:row,userId});}else{row=(await client.query(`INSERT INTO supplier_item_mappings(supplier_id,supplier_item_code,supplier_item_description,normalized_description,internal_product_id,material_group_id,brand,last_unit,last_price,last_seen_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW()) RETURNING *`,[supplierId,code,description,normalized,item.internal_product_id||null,item.material_group_id||null,item.brand||null,item.unit||null,item.unit_price??null])).rows[0];await logAudit(client,{entityType:'supplier_item_mapping',entityId:row.id,action:'mapping_created',newValue:row,userId});}return row;}

export async function confirmImport(payload,user){const items=Array.isArray(payload.items)?payload.items:[];if(!items.length)throw httpError(400,'Nenhum item para confirmar.');if(items.some(item=>!String(item.description||'').trim()))throw httpError(400,'Todos os itens confirmados precisam de descrição.');if(items.some(item=>!item.internal_product_id))throw httpError(400,'Vincule um Produto interno a todos os itens antes de confirmar a importação.',{code:'INTERNAL_PRODUCT_REQUIRED'});if(items.some(item=>!(Number(item.quantity)>0)))throw httpError(400,'Todos os itens precisam de quantidade válida.');if(payload.supplier_id&&items.some(item=>item.save_link)&&!hasPermission(user,'supplier_catalog.manage'))throw httpError(403,'Permissão para gerenciar vínculos do catálogo é obrigatória.');return transaction(async client=>{for(const item of items)item.unit=await normalizeMeasurementUnitCode(item.unit,client);const summary={valid:items.filter(i=>!(i.warnings?.length)).length,warnings:items.filter(i=>i.warnings?.length).length,invalid:0};const batch=(await client.query(`INSERT INTO purchase_import_batches(context,source_type,supplier_id,source_entity_id,valid_lines,warning_lines,invalid_lines,confirmed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[payload.context||'direct_quote',payload.source_type==='csv'?'csv':'text',payload.supplier_id||null,payload.source_entity_id||null,summary.valid,summary.warnings,summary.invalid,user.id])).rows[0];for(const [index,item] of items.entries()){const mapping=await upsertMapping(client,item,payload.supplier_id||null,user.id);await client.query(`INSERT INTO purchase_import_items(batch_id,line_number,supplier_item_code,description,quantity,unit,unit_price,total_price,brand,notes,internal_product_id,mapping_id,link_action,warnings) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,[batch.id,item.line_number||index+1,item.supplier_item_code||null,String(item.description).trim(),item.quantity,item.unit,item.unit_price??null,item.total_price??null,item.brand||null,item.notes||null,item.internal_product_id,mapping?.id||null,item.link_action||'selected',JSON.stringify(item.warnings||[])]);if(payload.supplier_id&&item.unit_price!=null)await recordPrice(client,{supplier_id:payload.supplier_id,mapping_id:mapping?.id||null,internal_product_id:item.internal_product_id,supplier_item_code:item.supplier_item_code||null,supplier_item_description:item.description,source:'manual_import',source_entity_id:batch.id,unit:item.unit,unit_price:item.unit_price,quantity:item.quantity,created_by:user.id});await logAudit(client,{entityType:'purchase_import',entityId:batch.id,action:'product_selected',newValue:{line_number:item.line_number||index+1,internal_product_id:item.internal_product_id,unit:item.unit},userId:user.id});}await logAudit(client,{entityType:'purchase_import',entityId:batch.id,action:'import_confirmed',newValue:{context:batch.context,item_count:items.length},userId:user.id});return{...batch,items};});}

export async function recordPrice(client,data){const row=(await client.query(`INSERT INTO supplier_item_price_history(supplier_id,mapping_id,internal_product_id,supplier_item_code,supplier_item_description,source,source_entity_id,currency,unit,unit_price,quantity,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,'BRL'),$9,$10,$11,$12) RETURNING *`,[data.supplier_id,data.mapping_id||null,data.internal_product_id||null,data.supplier_item_code||null,data.supplier_item_description,data.source,data.source_entity_id||null,data.currency||'BRL',data.unit||null,data.unit_price,data.quantity||null,data.created_by||null])).rows[0];if(data.mapping_id)await client.query('UPDATE supplier_item_mappings SET last_unit=COALESCE($1,last_unit),last_price=$2,last_seen_at=$3,updated_at=NOW() WHERE id=$4',[data.unit||null,data.unit_price,row.observed_at,data.mapping_id]);await logAudit(client,{entityType:'supplier_item_price',entityId:row.id,action:'price_recorded',newValue:{supplier_id:data.supplier_id,source:data.source,unit_price:data.unit_price},userId:data.created_by||null});return row;}

export async function listSupplierCatalog(supplierId,filters={}){const params=[supplierId];const where=['m.supplier_id=$1'];if(filters.status==='linked')where.push('m.internal_product_id IS NOT NULL AND m.is_active=TRUE');else if(filters.status==='unlinked')where.push('m.internal_product_id IS NULL AND m.is_active=TRUE');else if(filters.status==='inactive')where.push('m.is_active=FALSE');if(String(filters.search||'').trim()){params.push(`%${String(filters.search).trim()}%`);where.push(`(m.supplier_item_code ILIKE $${params.length} OR m.supplier_item_description ILIKE $${params.length} OR p.name ILIKE $${params.length} OR p.internal_code ILIKE $${params.length})`);}return(await query(`SELECT m.*,p.name internal_product_name,p.internal_code,p.is_active internal_product_active,(SELECT COUNT(*)::int FROM supplier_item_price_history ph WHERE ph.mapping_id=m.id) price_count FROM supplier_item_mappings m LEFT JOIN products p ON p.id=m.internal_product_id WHERE ${where.join(' AND ')} ORDER BY m.is_active DESC,m.last_seen_at DESC NULLS LAST,m.supplier_item_description`,params)).rows;}

export async function saveSupplierMapping(supplierId,payload,user){return transaction(async client=>{const item={...payload,description:payload.supplier_item_description||payload.description,save_link:true};const mapping=await upsertMapping(client,item,supplierId,user.id);if(!mapping)throw httpError(400,'Dados insuficientes para o vínculo.');return mapping;});}
export async function setSupplierMappingActive(supplierId,id,isActive,user){return transaction(async client=>{const previous=(await client.query('SELECT * FROM supplier_item_mappings WHERE id=$1 AND supplier_id=$2',[id,supplierId])).rows[0];if(!previous)throw httpError(404,'Item do catálogo não encontrado.');let row;try{row=(await client.query('UPDATE supplier_item_mappings SET is_active=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[Boolean(isActive),id])).rows[0];}catch(error){if(error.code==='23505')throw httpError(409,'Já existe um vínculo ativo para este código ou descrição.');throw error;}await logAudit(client,{entityType:'supplier_item_mapping',entityId:id,action:isActive?'mapping_reactivated':'mapping_deactivated',previousValue:previous,newValue:row,userId:user.id});return row;});}
export async function getSupplierPriceHistory(supplierId,mappingId){return(await query(`SELECT ph.*,p.name internal_product_name,u.name created_by_name FROM supplier_item_price_history ph LEFT JOIN products p ON p.id=ph.internal_product_id LEFT JOIN users u ON u.id=ph.created_by WHERE ph.supplier_id=$1 AND ($2::uuid IS NULL OR ph.mapping_id=$2) ORDER BY ph.observed_at DESC LIMIT 200`,[supplierId,mappingId||null])).rows;}

export async function createProductFromImport(payload,user){const name=String(payload.name||payload.description||'').trim().replace(/\s+/g,' ');if(!name)throw httpError(400,'Nome do Produto é obrigatório.');return transaction(async client=>{const normalized=normalizePurchaseText(name);const candidates=(await client.query(`SELECT id,name,internal_code,review_status FROM products WHERE is_active=TRUE AND (lower(regexp_replace(name,'[^[:alnum:]]','','g'))=lower(regexp_replace($1,'[^[:alnum:]]','','g')) OR name ILIKE '%'||$2||'%') ORDER BY review_status='pending_review' DESC,name LIMIT 8`,[name,normalized.split(' ').filter(word=>word.length>2)[0]||name])).rows;if(candidates.length&&!payload.confirm_duplicate)throw httpError(409,'Foram encontrados Produtos possivelmente duplicados. Revise e confirme para continuar.',{code:'POSSIBLE_PRODUCT_DUPLICATE',details:{candidates}});const shipping=(await client.query("SELECT id FROM sectors WHERE slug='expedicao' AND is_active=TRUE")).rows[0];if(!shipping)throw httpError(400,'Setor Expedição não encontrado.');let product;try{product=(await client.query(`INSERT INTO products(name,type,sector_id,default_volume_quantity,default_total_weight_kg,internal_code,review_status,creation_origin,preliminary_created_by,preliminary_created_at) VALUES($1,'resale',$2,1,1,$3,'pending_review','purchases',$4,NOW()) RETURNING *`,[name,shipping.id,String(payload.internal_code||'').trim()||null,user.id])).rows[0];}catch(error){if(error.code==='23505')throw httpError(409,'Já existe Produto com este código interno.');throw error;}await logAudit(client,{entityType:'product',entityId:product.id,action:'preliminary_created',newValue:{...product,duplicate_confirmed:Boolean(candidates.length)},userId:user.id});if(candidates.length)await logAudit(client,{entityType:'product',entityId:product.id,action:'possible_duplicate_confirmed',newValue:{candidate_ids:candidates.map(item=>item.id)},userId:user.id});return{...product,duplicate_candidates:candidates};});}
export async function listImportProducts(search='',filters={}){const value=String(search||'').trim();return(await query(`SELECT p.id,p.name,p.internal_code,p.is_active,p.measurement_unit_code,p.review_status,p.creation_origin,p.preliminary_created_by,pt.name type_name,EXISTS(SELECT 1 FROM product_images image WHERE image.product_id=p.id) has_photo,COALESCE(string_agg(DISTINCT mg.name,', ') FILTER(WHERE mg.name IS NOT NULL),'') material_group_name FROM products p LEFT JOIN product_types pt ON pt.code=p.type LEFT JOIN supplier_item_mappings sim ON sim.internal_product_id=p.id LEFT JOIN material_groups mg ON mg.id=sim.material_group_id WHERE p.is_active=TRUE AND ($1='' OR p.name ILIKE '%'||$1||'%' OR p.internal_code ILIKE '%'||$1||'%' OR pt.name ILIKE '%'||$1||'%' OR mg.name ILIKE '%'||$1||'%') GROUP BY p.id,pt.name ORDER BY p.review_status='pending_review' DESC,p.name LIMIT 80`,[value])).rows;}
