-- Alinha somente metadados do catálogo. Códigos e IDs existentes são preservados.
INSERT INTO permissions (code, name, description, group_name)
VALUES
('advances.approve', 'Aprovar listas de vales', 'Permite aprovar listas de vales.', 'Administrativo'),
  ('advances.audit.view', 'Ver auditoria de vales', 'Permite ver auditoria de vales.', 'Administrativo'),
  ('advances.create', 'Criar listas de vales', 'Permite criar listas de vales.', 'Administrativo'),
  ('advances.create_individual', 'Lançar vale individual', 'Permite lançar vale individual.', 'Administrativo'),
  ('advances.cycles.close', 'Fechar ciclos de vales', 'Permite fechar ciclos de vales.', 'Administrativo'),
  ('advances.cycles.create', 'Iniciar ciclos de vales', 'Permite iniciar ciclos de vales.', 'Administrativo'),
  ('advances.cycles.view', 'Ver ciclos de vales', 'Permite ver ciclos de vales.', 'Administrativo'),
  ('advances.edit_own_list', 'Editar própria lista de vales', 'Permite editar própria lista de vales.', 'Administrativo'),
  ('advances.installments.convert', 'Parcelar vale existente', 'Permite parcelar vale existente.', 'Administrativo'),
  ('advances.installments.create', 'Criar parcelamentos de vales', 'Permite criar parcelamentos de vales.', 'Administrativo'),
  ('advances.installments.view', 'Ver parcelamentos de vales', 'Permite ver parcelamentos de vales.', 'Administrativo'),
  ('advances.limit_lookup', 'Consultar limite de vales', 'Permite consultar limite de vales.', 'Administrativo'),
  ('advances.lists.delete', 'Excluir listas de vales', 'Permite excluir listas de vales.', 'Administrativo'),
  ('advances.manage', 'Gerenciar vales', 'Permite gerenciar vales.', 'Administrativo'),
  ('advances.override_limits', 'Exceder limites de vales', 'Permite exceder limites de vales.', 'Administrativo'),
  ('advances.reports.cycles', 'Ver ciclos anteriores de vales', 'Permite ver ciclos anteriores de vales.', 'Administrativo'),
  ('advances.reports.general', 'Ver relatório geral de vales', 'Permite ver relatório geral de vales.', 'Administrativo'),
  ('advances.reports.individual', 'Ver extrato individual de vales', 'Permite ver extrato individual de vales.', 'Administrativo'),
  ('advances.reports.view', 'Ver relatórios de vales', 'Permite ver relatórios de vales.', 'Administrativo'),
  ('advances.review', 'Revisar listas de vales', 'Permite revisar listas de vales.', 'Administrativo'),
  ('advances.view', 'Ver vales', 'Permite ver vales.', 'Administrativo'),
  ('awards.create', 'Criar prêmios', 'Permite criar prêmios.', 'Administrativo'),
  ('awards.delete', 'Excluir prêmios', 'Permite excluir prêmios.', 'Administrativo'),
  ('awards.edit', 'Editar prêmios', 'Permite editar prêmios.', 'Administrativo'),
  ('awards.pdf', 'Baixar termos de prêmios', 'Permite baixar termos de prêmios.', 'Administrativo'),
  ('awards.view', 'Ver prêmios', 'Permite ver prêmios.', 'Administrativo'),
  ('commercial.customers.create', 'Criar clientes', 'Permite criar clientes.', 'Comercial'),
  ('commercial.customers.edit', 'Editar, ativar ou inativar clientes', 'Permite editar, ativar ou inativar clientes.', 'Comercial'),
  ('commercial.customers.view', 'Ver clientes', 'Permite ver clientes.', 'Comercial'),
  ('company_settings.edit', 'Editar configurações da empresa', 'Permite editar configurações da empresa.', 'Configurações'),
  ('company_settings.view', 'Ver configurações da empresa', 'Permite ver configurações da empresa.', 'Configurações'),
  ('dashboard.view', 'Ver dashboard', 'Permite ver dashboard.', 'Dashboard'),
  ('employees.create', 'Criar funcionários', 'Permite criar funcionários.', 'Administrativo'),
  ('employees.deactivate', 'Desativar funcionários', 'Permite desativar funcionários.', 'Administrativo'),
  ('employees.dependents.manage', 'Gerenciar dependentes', 'Permite gerenciar dependentes.', 'Administrativo'),
  ('employees.dependents.view', 'Ver dependentes', 'Permite ver dependentes.', 'Administrativo'),
  ('employees.documents.manage', 'Gerenciar documentos de funcionários', 'Permite gerenciar documentos de funcionários.', 'Administrativo'),
  ('employees.documents.view', 'Ver documentos de funcionários', 'Permite ver documentos de funcionários.', 'Administrativo'),
  ('employees.edit', 'Editar funcionários', 'Permite editar funcionários.', 'Administrativo'),
  ('employees.manage', 'Gerenciar funcionários', 'Permite gerenciar funcionários.', 'Administrativo'),
  ('employees.meal_allowance.manage', 'Gerenciar vale-alimentação', 'Permite gerenciar vale-alimentação.', 'Administrativo'),
  ('employees.meal_allowance.view', 'Ver vale-alimentação', 'Permite ver vale-alimentação.', 'Administrativo'),
  ('employees.profile.print', 'Imprimir ficha de funcionário', 'Permite imprimir ficha de funcionário.', 'Administrativo'),
  ('employees.salary.manage', 'Gerenciar salário de funcionários', 'Permite gerenciar salário de funcionários.', 'Administrativo'),
  ('employees.salary.view', 'Ver salário de funcionários', 'Permite ver salário de funcionários.', 'Administrativo'),
  ('employees.view', 'Ver funcionários', 'Permite ver funcionários.', 'Administrativo'),
  ('labels.mark_without_label', 'Marcar sem etiqueta', 'Permite marcar sem etiqueta.', 'Expedição'),
  ('labels.print', 'Imprimir etiquetas', 'Permite imprimir etiquetas.', 'Expedição'),
  ('labels.reprint', 'Reimprimir etiquetas', 'Permite reimprimir etiquetas.', 'Expedição'),
  ('labels.view', 'Ver fila de etiquetas', 'Permite ver fila de etiquetas.', 'Expedição'),
  ('orders.create', 'Criar ordem de produção', 'Permite criar ordem de produção.', 'Produção'),
  ('orders.delete', 'Excluir ordem de produção', 'Permite excluir ordem de produção.', 'Produção'),
  ('orders.edit', 'Editar ordem de produção', 'Permite editar ordem de produção.', 'Produção'),
  ('orders.history.view', 'Ver histórico de produção', 'Permite ver histórico de produção.', 'Produção'),
  ('orders.view', 'Ver ordens de produção', 'Permite ver ordens de produção.', 'Produção'),
  ('products.create', 'Criar produtos', 'Permite criar produtos.', 'Estoque'),
  ('products.delete', 'Excluir produtos', 'Permite excluir produtos.', 'Estoque'),
  ('products.edit', 'Editar produtos', 'Permite editar produtos.', 'Estoque'),
  ('products.types.manage', 'Gerenciar tipos de produto', 'Permite gerenciar tipos de produto.', 'Estoque'),
  ('products.view', 'Ver produtos', 'Permite ver produtos.', 'Estoque'),
  ('purchase_imports.create_product', 'Criar produto preliminar em Compras', 'Permite criar produto preliminar em Compras.', 'Compras'),
  ('purchase_items.import', 'Importar itens de compras', 'Permite importar itens de compras.', 'Compras'),
  ('purchase_quotes.choose_supplier', 'Escolher fornecedores em cotações', 'Permite escolher fornecedores em cotações.', 'Compras'),
  ('purchase_quotes.create', 'Criar solicitações de cotação', 'Permite criar solicitações de cotação.', 'Compras'),
  ('purchase_quotes.manage', 'Gerenciar cotações', 'Permite gerenciar cotações.', 'Compras'),
  ('purchase_quotes.pdf', 'Baixar PDFs de cotação', 'Permite baixar PDFs de cotação.', 'Compras'),
  ('purchase_quotes.register_response', 'Registrar propostas de fornecedores', 'Permite registrar propostas de fornecedores.', 'Compras'),
  ('purchase_quotes.send', 'Registrar envio de cotações', 'Permite registrar envio de cotações.', 'Compras'),
  ('purchase_quotes.view', 'Ver cotações', 'Permite ver cotações.', 'Compras'),
  ('purchases.approve', 'Aprovar solicitações de compra', 'Permite aprovar solicitações de compra.', 'Compras'),
  ('purchases.cancel', 'Cancelar solicitações e compras', 'Permite cancelar solicitações e compras.', 'Compras'),
  ('purchases.create_direct', 'Criar compras diretas', 'Permite criar compras diretas.', 'Compras'),
  ('purchases.create_preapproved', 'Criar solicitação pré-aprovada', 'Permite criar solicitação pré-aprovada.', 'Compras'),
  ('purchases.create_request', 'Criar solicitações de compra', 'Permite criar solicitações de compra.', 'Compras'),
  ('purchases.edit_own_request', 'Editar solicitações próprias', 'Permite editar solicitações próprias.', 'Compras'),
  ('purchases.receive', 'Registrar recebimentos', 'Permite registrar recebimentos.', 'Compras'),
  ('purchases.view', 'Ver compras e solicitações', 'Permite ver compras e solicitações.', 'Compras'),
  ('purchases.view_values', 'Ver valores de compras', 'Permite ver valores de compras.', 'Compras'),
  ('roles.manage', 'Gerenciar perfis', 'Permite gerenciar perfis.', 'Configurações'),
  ('roles.view', 'Ver perfis', 'Permite ver perfis.', 'Configurações'),
  ('sectors.manage', 'Gerenciar setores', 'Permite gerenciar setores.', 'Configurações'),
  ('sectors.view', 'Ver setores', 'Permite ver setores.', 'Configurações'),
  ('services.complete', 'Concluir serviços', 'Permite concluir serviços.', 'Produção'),
  ('services.view', 'Ver serviços', 'Permite ver serviços.', 'Produção'),
  ('shipping.audit.view', 'Ver auditoria de expedições', 'Permite ver auditoria de expedições.', 'Expedição'),
  ('shipping.confirm', 'Confirmar expedição', 'Permite confirmar expedição.', 'Expedição'),
  ('shipping.ready_admin.view', 'Ver vendas prontas', 'Permite ver vendas prontas.', 'Expedição'),
  ('shipping.view', 'Ver expedição', 'Permite ver expedição.', 'Expedição'),
  ('supplier_catalog.manage', 'Gerenciar vínculos do catálogo de fornecedores', 'Permite gerenciar vínculos do catálogo de fornecedores.', 'Compras'),
  ('supplier_catalog.view', 'Visualizar catálogo vinculado', 'Permite visualizar catálogo vinculado.', 'Compras'),
  ('supplier_groups.manage', 'Gerenciar grupos de materiais', 'Permite gerenciar grupos de materiais.', 'Compras'),
  ('supplier_prices.view', 'Visualizar histórico de preços de fornecedores', 'Permite visualizar histórico de preços de fornecedores.', 'Compras'),
  ('suppliers.create', 'Criar fornecedores', 'Permite criar fornecedores.', 'Compras'),
  ('suppliers.deactivate', 'Desativar ou reativar fornecedores', 'Permite desativar ou reativar fornecedores.', 'Compras'),
  ('suppliers.edit', 'Editar fornecedores', 'Permite editar fornecedores.', 'Compras'),
  ('suppliers.manage', 'Gerenciar fornecedores', 'Permite gerenciar fornecedores.', 'Compras'),
  ('suppliers.view', 'Ver fornecedores', 'Permite ver fornecedores.', 'Compras'),
  ('tv.view', 'Ver painel de produção', 'Permite ver painel de produção.', 'Produção'),
  ('users.approve', 'Aprovar usuários', 'Permite aprovar usuários.', 'Configurações'),
  ('users.change_password', 'Alterar senhas', 'Permite alterar senhas.', 'Configurações'),
  ('users.manage', 'Gerenciar usuários', 'Permite gerenciar usuários.', 'Configurações'),
  ('users.view', 'Ver usuários', 'Permite ver usuários.', 'Configurações')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  group_name = EXCLUDED.group_name;

-- O perfil Administrador recebe todas as permissões conhecidas. Nenhum vínculo de
-- outro perfil é criado, removido ou substituído.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.slug = 'admin'
ON CONFLICT DO NOTHING;

